// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Block {
    #[prost(bytes = "vec", tag = "1")]
    pub cid: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub container: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for Block {
    const NAME: &'static str = "Block";
    const PACKAGE: &'static str = "bitswap";
    fn full_name() -> ::prost::alloc::string::String {
        "bitswap.Block".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/bitswap.Block".into()
    }
}
