// This file is @generated by prost-build.
/// HistoricalInfo contains header and validator information for a given block.
/// It is stored as part of staking module's state, which persists the `n` most
/// recent HistoricalInfo
/// (`n` is set by the staking module's `historical_entries` parameter).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HistoricalInfo {
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<
        ::celestia_tendermint_proto::v0_34::types::Header,
    >,
    #[prost(message, repeated, tag = "2")]
    pub valset: ::prost::alloc::vec::Vec<Validator>,
}
impl ::prost::Name for HistoricalInfo {
    const NAME: &'static str = "HistoricalInfo";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.HistoricalInfo".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.HistoricalInfo".into()
    }
}
/// CommissionRates defines the initial commission rates to be used for creating
/// a validator.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommissionRates {
    /// rate is the commission rate charged to delegators, as a fraction.
    #[prost(string, tag = "1")]
    pub rate: ::prost::alloc::string::String,
    /// max_rate defines the maximum commission rate which validator can ever charge, as a fraction.
    #[prost(string, tag = "2")]
    pub max_rate: ::prost::alloc::string::String,
    /// max_change_rate defines the maximum daily increase of the validator commission, as a fraction.
    #[prost(string, tag = "3")]
    pub max_change_rate: ::prost::alloc::string::String,
}
impl ::prost::Name for CommissionRates {
    const NAME: &'static str = "CommissionRates";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.CommissionRates".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.CommissionRates".into()
    }
}
/// Commission defines commission parameters for a given validator.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Commission {
    /// commission_rates defines the initial commission rates to be used for creating a validator.
    #[prost(message, optional, tag = "1")]
    pub commission_rates: ::core::option::Option<CommissionRates>,
    /// update_time is the last time the commission rate was changed.
    #[prost(message, optional, tag = "2")]
    pub update_time: ::core::option::Option<
        ::celestia_tendermint_proto::google::protobuf::Timestamp,
    >,
}
impl ::prost::Name for Commission {
    const NAME: &'static str = "Commission";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.Commission".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.Commission".into()
    }
}
/// Description defines a validator description.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Description {
    /// moniker defines a human-readable name for the validator.
    #[prost(string, tag = "1")]
    pub moniker: ::prost::alloc::string::String,
    /// identity defines an optional identity signature (ex. UPort or Keybase).
    #[prost(string, tag = "2")]
    pub identity: ::prost::alloc::string::String,
    /// website defines an optional website link.
    #[prost(string, tag = "3")]
    pub website: ::prost::alloc::string::String,
    /// security_contact defines an optional email for security contact.
    #[prost(string, tag = "4")]
    pub security_contact: ::prost::alloc::string::String,
    /// details define other optional details.
    #[prost(string, tag = "5")]
    pub details: ::prost::alloc::string::String,
}
impl ::prost::Name for Description {
    const NAME: &'static str = "Description";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.Description".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.Description".into()
    }
}
/// Validator defines a validator, together with the total amount of the
/// Validator's bond shares and their exchange rate to coins. Slashing results in
/// a decrease in the exchange rate, allowing correct calculation of future
/// undelegations without iterating over delegators. When coins are delegated to
/// this validator, the validator is credited with a delegation whose number of
/// bond shares is based on the amount of coins delegated divided by the current
/// exchange rate. Voting power can be calculated as total bonded shares
/// multiplied by exchange rate.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Validator {
    /// operator_address defines the address of the validator's operator; bech encoded in JSON.
    #[prost(string, tag = "1")]
    pub operator_address: ::prost::alloc::string::String,
    /// consensus_pubkey is the consensus public key of the validator, as a Protobuf Any.
    #[prost(message, optional, tag = "2")]
    pub consensus_pubkey: ::core::option::Option<::pbjson_types::Any>,
    /// jailed defined whether the validator has been jailed from bonded status or not.
    #[prost(bool, tag = "3")]
    pub jailed: bool,
    /// status is the validator status (bonded/unbonding/unbonded).
    #[prost(enumeration = "BondStatus", tag = "4")]
    pub status: i32,
    /// tokens define the delegated tokens (incl. self-delegation).
    #[prost(string, tag = "5")]
    pub tokens: ::prost::alloc::string::String,
    /// delegator_shares defines total shares issued to a validator's delegators.
    #[prost(string, tag = "6")]
    pub delegator_shares: ::prost::alloc::string::String,
    /// description defines the description terms for the validator.
    #[prost(message, optional, tag = "7")]
    pub description: ::core::option::Option<Description>,
    /// unbonding_height defines, if unbonding, the height at which this validator has begun unbonding.
    #[prost(int64, tag = "8")]
    pub unbonding_height: i64,
    /// unbonding_time defines, if unbonding, the min time for the validator to complete unbonding.
    #[prost(message, optional, tag = "9")]
    pub unbonding_time: ::core::option::Option<
        ::celestia_tendermint_proto::google::protobuf::Timestamp,
    >,
    /// commission defines the commission parameters.
    #[prost(message, optional, tag = "10")]
    pub commission: ::core::option::Option<Commission>,
    /// min_self_delegation is the validator's self declared minimum self delegation.
    ///
    /// Since: cosmos-sdk 0.46
    #[prost(string, tag = "11")]
    pub min_self_delegation: ::prost::alloc::string::String,
}
impl ::prost::Name for Validator {
    const NAME: &'static str = "Validator";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.Validator".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.Validator".into()
    }
}
/// ValAddresses defines a repeated set of validator addresses.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValAddresses {
    #[prost(string, repeated, tag = "1")]
    pub addresses: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
impl ::prost::Name for ValAddresses {
    const NAME: &'static str = "ValAddresses";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.ValAddresses".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.ValAddresses".into()
    }
}
/// DVPair is struct that just has a delegator-validator pair with no other data.
/// It is intended to be used as a marshalable pointer. For example, a DVPair can
/// be used to construct the key to getting an UnbondingDelegation from state.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DvPair {
    #[prost(string, tag = "1")]
    pub delegator_address: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub validator_address: ::prost::alloc::string::String,
}
impl ::prost::Name for DvPair {
    const NAME: &'static str = "DVPair";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.DVPair".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.DVPair".into()
    }
}
/// DVPairs defines an array of DVPair objects.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DvPairs {
    #[prost(message, repeated, tag = "1")]
    pub pairs: ::prost::alloc::vec::Vec<DvPair>,
}
impl ::prost::Name for DvPairs {
    const NAME: &'static str = "DVPairs";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.DVPairs".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.DVPairs".into()
    }
}
/// DVVTriplet is struct that just has a delegator-validator-validator triplet
/// with no other data. It is intended to be used as a marshalable pointer. For
/// example, a DVVTriplet can be used to construct the key to getting a
/// Redelegation from state.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DvvTriplet {
    #[prost(string, tag = "1")]
    pub delegator_address: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub validator_src_address: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub validator_dst_address: ::prost::alloc::string::String,
}
impl ::prost::Name for DvvTriplet {
    const NAME: &'static str = "DVVTriplet";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.DVVTriplet".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.DVVTriplet".into()
    }
}
/// DVVTriplets defines an array of DVVTriplet objects.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DvvTriplets {
    #[prost(message, repeated, tag = "1")]
    pub triplets: ::prost::alloc::vec::Vec<DvvTriplet>,
}
impl ::prost::Name for DvvTriplets {
    const NAME: &'static str = "DVVTriplets";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.DVVTriplets".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.DVVTriplets".into()
    }
}
/// Delegation represents the bond with tokens held by an account. It is
/// owned by one delegator, and is associated with the voting power of one
/// validator.
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Delegation {
    /// delegator_address is the bech32-encoded address of the delegator.
    #[prost(string, tag = "1")]
    pub delegator_address: ::prost::alloc::string::String,
    /// validator_address is the bech32-encoded address of the validator.
    #[prost(string, tag = "2")]
    pub validator_address: ::prost::alloc::string::String,
    /// shares define the delegation shares received.
    #[prost(string, tag = "3")]
    pub shares: ::prost::alloc::string::String,
}
impl ::prost::Name for Delegation {
    const NAME: &'static str = "Delegation";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.Delegation".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.Delegation".into()
    }
}
/// UnbondingDelegation stores all of a single delegator's unbonding bonds
/// for a single validator in an time-ordered list.
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnbondingDelegation {
    /// delegator_address is the bech32-encoded address of the delegator.
    #[prost(string, tag = "1")]
    pub delegator_address: ::prost::alloc::string::String,
    /// validator_address is the bech32-encoded address of the validator.
    #[prost(string, tag = "2")]
    pub validator_address: ::prost::alloc::string::String,
    /// entries are the unbonding delegation entries.
    ///
    /// unbonding delegation entries
    #[prost(message, repeated, tag = "3")]
    pub entries: ::prost::alloc::vec::Vec<UnbondingDelegationEntry>,
}
impl ::prost::Name for UnbondingDelegation {
    const NAME: &'static str = "UnbondingDelegation";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.UnbondingDelegation".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.UnbondingDelegation".into()
    }
}
/// UnbondingDelegationEntry defines an unbonding object with relevant metadata.
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnbondingDelegationEntry {
    /// creation_height is the height which the unbonding took place.
    #[prost(int64, tag = "1")]
    pub creation_height: i64,
    /// completion_time is the unix time for unbonding completion.
    #[prost(message, optional, tag = "2")]
    #[serde(with = "crate::serializers::option_timestamp")]
    pub completion_time: ::core::option::Option<
        ::celestia_tendermint_proto::google::protobuf::Timestamp,
    >,
    /// initial_balance defines the tokens initially scheduled to receive at completion.
    #[prost(string, tag = "3")]
    pub initial_balance: ::prost::alloc::string::String,
    /// balance defines the tokens to receive at completion.
    #[prost(string, tag = "4")]
    pub balance: ::prost::alloc::string::String,
}
impl ::prost::Name for UnbondingDelegationEntry {
    const NAME: &'static str = "UnbondingDelegationEntry";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.UnbondingDelegationEntry".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.UnbondingDelegationEntry".into()
    }
}
/// RedelegationEntry defines a redelegation object with relevant metadata.
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RedelegationEntry {
    /// creation_height  defines the height which the redelegation took place.
    #[prost(int64, tag = "1")]
    pub creation_height: i64,
    /// completion_time defines the unix time for redelegation completion.
    #[prost(message, optional, tag = "2")]
    #[serde(with = "crate::serializers::option_timestamp")]
    pub completion_time: ::core::option::Option<
        ::celestia_tendermint_proto::google::protobuf::Timestamp,
    >,
    /// initial_balance defines the initial balance when redelegation started.
    #[prost(string, tag = "3")]
    pub initial_balance: ::prost::alloc::string::String,
    /// shares_dst is the amount of destination-validator shares created by redelegation.
    #[prost(string, tag = "4")]
    pub shares_dst: ::prost::alloc::string::String,
}
impl ::prost::Name for RedelegationEntry {
    const NAME: &'static str = "RedelegationEntry";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.RedelegationEntry".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.RedelegationEntry".into()
    }
}
/// Redelegation contains the list of a particular delegator's redelegating bonds
/// from a particular source validator to a particular destination validator.
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Redelegation {
    /// delegator_address is the bech32-encoded address of the delegator.
    #[prost(string, tag = "1")]
    pub delegator_address: ::prost::alloc::string::String,
    /// validator_src_address is the validator redelegation source operator address.
    #[prost(string, tag = "2")]
    pub validator_src_address: ::prost::alloc::string::String,
    /// validator_dst_address is the validator redelegation destination operator address.
    #[prost(string, tag = "3")]
    pub validator_dst_address: ::prost::alloc::string::String,
    /// entries are the redelegation entries.
    ///
    /// redelegation entries
    #[prost(message, repeated, tag = "4")]
    pub entries: ::prost::alloc::vec::Vec<RedelegationEntry>,
}
impl ::prost::Name for Redelegation {
    const NAME: &'static str = "Redelegation";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.Redelegation".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.Redelegation".into()
    }
}
/// Params defines the parameters for the staking module.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Params {
    /// unbonding_time is the time duration of unbonding.
    #[prost(message, optional, tag = "1")]
    pub unbonding_time: ::core::option::Option<
        ::celestia_tendermint_proto::google::protobuf::Duration,
    >,
    /// max_validators is the maximum number of validators.
    #[prost(uint32, tag = "2")]
    pub max_validators: u32,
    /// max_entries is the max entries for either unbonding delegation or redelegation (per pair/trio).
    #[prost(uint32, tag = "3")]
    pub max_entries: u32,
    /// historical_entries is the number of historical entries to persist.
    #[prost(uint32, tag = "4")]
    pub historical_entries: u32,
    /// bond_denom defines the bondable coin denomination.
    #[prost(string, tag = "5")]
    pub bond_denom: ::prost::alloc::string::String,
    /// min_commission_rate is the chain-wide minimum commission rate that a validator can charge their delegators
    #[prost(string, tag = "6")]
    pub min_commission_rate: ::prost::alloc::string::String,
}
impl ::prost::Name for Params {
    const NAME: &'static str = "Params";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.Params".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.Params".into()
    }
}
/// DelegationResponse is equivalent to Delegation except that it contains a
/// balance in addition to shares which is more suitable for client responses.
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DelegationResponse {
    #[prost(message, optional, tag = "1")]
    pub delegation: ::core::option::Option<Delegation>,
    #[prost(message, optional, tag = "2")]
    pub balance: ::core::option::Option<super::super::base::v1beta1::Coin>,
}
impl ::prost::Name for DelegationResponse {
    const NAME: &'static str = "DelegationResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.DelegationResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.DelegationResponse".into()
    }
}
/// RedelegationEntryResponse is equivalent to a RedelegationEntry except that it
/// contains a balance in addition to shares which is more suitable for client
/// responses.
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RedelegationEntryResponse {
    #[prost(message, optional, tag = "1")]
    pub redelegation_entry: ::core::option::Option<RedelegationEntry>,
    #[prost(string, tag = "4")]
    pub balance: ::prost::alloc::string::String,
}
impl ::prost::Name for RedelegationEntryResponse {
    const NAME: &'static str = "RedelegationEntryResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.RedelegationEntryResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.RedelegationEntryResponse".into()
    }
}
/// RedelegationResponse is equivalent to a Redelegation except that its entries
/// contain a balance in addition to shares which is more suitable for client
/// responses.
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RedelegationResponse {
    #[prost(message, optional, tag = "1")]
    pub redelegation: ::core::option::Option<Redelegation>,
    #[prost(message, repeated, tag = "2")]
    pub entries: ::prost::alloc::vec::Vec<RedelegationEntryResponse>,
}
impl ::prost::Name for RedelegationResponse {
    const NAME: &'static str = "RedelegationResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.RedelegationResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.RedelegationResponse".into()
    }
}
/// Pool is used for tracking bonded and not-bonded token supply of the bond
/// denomination.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pool {
    #[prost(string, tag = "1")]
    pub not_bonded_tokens: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub bonded_tokens: ::prost::alloc::string::String,
}
impl ::prost::Name for Pool {
    const NAME: &'static str = "Pool";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.Pool".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.Pool".into()
    }
}
/// BondStatus is the status of a validator.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BondStatus {
    /// UNSPECIFIED defines an invalid validator status.
    Unspecified = 0,
    /// UNBONDED defines a validator that is not bonded.
    Unbonded = 1,
    /// UNBONDING defines a validator that is unbonding.
    Unbonding = 2,
    /// BONDED defines a validator that is bonded.
    Bonded = 3,
}
impl BondStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "BOND_STATUS_UNSPECIFIED",
            Self::Unbonded => "BOND_STATUS_UNBONDED",
            Self::Unbonding => "BOND_STATUS_UNBONDING",
            Self::Bonded => "BOND_STATUS_BONDED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BOND_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "BOND_STATUS_UNBONDED" => Some(Self::Unbonded),
            "BOND_STATUS_UNBONDING" => Some(Self::Unbonding),
            "BOND_STATUS_BONDED" => Some(Self::Bonded),
            _ => None,
        }
    }
}
/// QueryValidatorsRequest is request type for Query/Validators RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryValidatorsRequest {
    /// status enables to query for validators matching a given status.
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    /// pagination defines an optional pagination for the request.
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<
        super::super::base::query::v1beta1::PageRequest,
    >,
}
impl ::prost::Name for QueryValidatorsRequest {
    const NAME: &'static str = "QueryValidatorsRequest";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryValidatorsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryValidatorsRequest".into()
    }
}
/// QueryValidatorsResponse is response type for the Query/Validators RPC method
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryValidatorsResponse {
    /// validators contains all the queried validators.
    #[prost(message, repeated, tag = "1")]
    pub validators: ::prost::alloc::vec::Vec<Validator>,
    /// pagination defines the pagination in the response.
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<
        super::super::base::query::v1beta1::PageResponse,
    >,
}
impl ::prost::Name for QueryValidatorsResponse {
    const NAME: &'static str = "QueryValidatorsResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryValidatorsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryValidatorsResponse".into()
    }
}
/// QueryValidatorRequest is response type for the Query/Validator RPC method
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryValidatorRequest {
    /// validator_addr defines the validator address to query for.
    #[prost(string, tag = "1")]
    pub validator_addr: ::prost::alloc::string::String,
}
impl ::prost::Name for QueryValidatorRequest {
    const NAME: &'static str = "QueryValidatorRequest";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryValidatorRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryValidatorRequest".into()
    }
}
/// QueryValidatorResponse is response type for the Query/Validator RPC method
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryValidatorResponse {
    /// validator defines the validator info.
    #[prost(message, optional, tag = "1")]
    pub validator: ::core::option::Option<Validator>,
}
impl ::prost::Name for QueryValidatorResponse {
    const NAME: &'static str = "QueryValidatorResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryValidatorResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryValidatorResponse".into()
    }
}
/// QueryValidatorDelegationsRequest is request type for the
/// Query/ValidatorDelegations RPC method
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryValidatorDelegationsRequest {
    /// validator_addr defines the validator address to query for.
    #[prost(string, tag = "1")]
    pub validator_addr: ::prost::alloc::string::String,
    /// pagination defines an optional pagination for the request.
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<
        super::super::base::query::v1beta1::PageRequest,
    >,
}
impl ::prost::Name for QueryValidatorDelegationsRequest {
    const NAME: &'static str = "QueryValidatorDelegationsRequest";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryValidatorDelegationsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryValidatorDelegationsRequest".into()
    }
}
/// QueryValidatorDelegationsResponse is response type for the
/// Query/ValidatorDelegations RPC method
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryValidatorDelegationsResponse {
    #[prost(message, repeated, tag = "1")]
    pub delegation_responses: ::prost::alloc::vec::Vec<DelegationResponse>,
    /// pagination defines the pagination in the response.
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<
        super::super::base::query::v1beta1::PageResponse,
    >,
}
impl ::prost::Name for QueryValidatorDelegationsResponse {
    const NAME: &'static str = "QueryValidatorDelegationsResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryValidatorDelegationsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryValidatorDelegationsResponse".into()
    }
}
/// QueryValidatorUnbondingDelegationsRequest is required type for the
/// Query/ValidatorUnbondingDelegations RPC method
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryValidatorUnbondingDelegationsRequest {
    /// validator_addr defines the validator address to query for.
    #[prost(string, tag = "1")]
    pub validator_addr: ::prost::alloc::string::String,
    /// pagination defines an optional pagination for the request.
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<
        super::super::base::query::v1beta1::PageRequest,
    >,
}
impl ::prost::Name for QueryValidatorUnbondingDelegationsRequest {
    const NAME: &'static str = "QueryValidatorUnbondingDelegationsRequest";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryValidatorUnbondingDelegationsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryValidatorUnbondingDelegationsRequest".into()
    }
}
/// QueryValidatorUnbondingDelegationsResponse is response type for the
/// Query/ValidatorUnbondingDelegations RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryValidatorUnbondingDelegationsResponse {
    #[prost(message, repeated, tag = "1")]
    pub unbonding_responses: ::prost::alloc::vec::Vec<UnbondingDelegation>,
    /// pagination defines the pagination in the response.
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<
        super::super::base::query::v1beta1::PageResponse,
    >,
}
impl ::prost::Name for QueryValidatorUnbondingDelegationsResponse {
    const NAME: &'static str = "QueryValidatorUnbondingDelegationsResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryValidatorUnbondingDelegationsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryValidatorUnbondingDelegationsResponse".into()
    }
}
/// QueryDelegationRequest is request type for the Query/Delegation RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryDelegationRequest {
    /// delegator_addr defines the delegator address to query for.
    #[prost(string, tag = "1")]
    pub delegator_addr: ::prost::alloc::string::String,
    /// validator_addr defines the validator address to query for.
    #[prost(string, tag = "2")]
    pub validator_addr: ::prost::alloc::string::String,
}
impl ::prost::Name for QueryDelegationRequest {
    const NAME: &'static str = "QueryDelegationRequest";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryDelegationRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryDelegationRequest".into()
    }
}
/// QueryDelegationResponse is response type for the Query/Delegation RPC method.
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryDelegationResponse {
    /// delegation_responses defines the delegation info of a delegation.
    #[prost(message, optional, tag = "1")]
    pub delegation_response: ::core::option::Option<DelegationResponse>,
}
impl ::prost::Name for QueryDelegationResponse {
    const NAME: &'static str = "QueryDelegationResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryDelegationResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryDelegationResponse".into()
    }
}
/// QueryUnbondingDelegationRequest is request type for the
/// Query/UnbondingDelegation RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryUnbondingDelegationRequest {
    /// delegator_addr defines the delegator address to query for.
    #[prost(string, tag = "1")]
    pub delegator_addr: ::prost::alloc::string::String,
    /// validator_addr defines the validator address to query for.
    #[prost(string, tag = "2")]
    pub validator_addr: ::prost::alloc::string::String,
}
impl ::prost::Name for QueryUnbondingDelegationRequest {
    const NAME: &'static str = "QueryUnbondingDelegationRequest";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryUnbondingDelegationRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryUnbondingDelegationRequest".into()
    }
}
/// QueryDelegationResponse is response type for the Query/UnbondingDelegation
/// RPC method.
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryUnbondingDelegationResponse {
    /// unbond defines the unbonding information of a delegation.
    #[prost(message, optional, tag = "1")]
    pub unbond: ::core::option::Option<UnbondingDelegation>,
}
impl ::prost::Name for QueryUnbondingDelegationResponse {
    const NAME: &'static str = "QueryUnbondingDelegationResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryUnbondingDelegationResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryUnbondingDelegationResponse".into()
    }
}
/// QueryDelegatorDelegationsRequest is request type for the
/// Query/DelegatorDelegations RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryDelegatorDelegationsRequest {
    /// delegator_addr defines the delegator address to query for.
    #[prost(string, tag = "1")]
    pub delegator_addr: ::prost::alloc::string::String,
    /// pagination defines an optional pagination for the request.
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<
        super::super::base::query::v1beta1::PageRequest,
    >,
}
impl ::prost::Name for QueryDelegatorDelegationsRequest {
    const NAME: &'static str = "QueryDelegatorDelegationsRequest";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryDelegatorDelegationsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryDelegatorDelegationsRequest".into()
    }
}
/// QueryDelegatorDelegationsResponse is response type for the
/// Query/DelegatorDelegations RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryDelegatorDelegationsResponse {
    /// delegation_responses defines all the delegations' info of a delegator.
    #[prost(message, repeated, tag = "1")]
    pub delegation_responses: ::prost::alloc::vec::Vec<DelegationResponse>,
    /// pagination defines the pagination in the response.
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<
        super::super::base::query::v1beta1::PageResponse,
    >,
}
impl ::prost::Name for QueryDelegatorDelegationsResponse {
    const NAME: &'static str = "QueryDelegatorDelegationsResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryDelegatorDelegationsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryDelegatorDelegationsResponse".into()
    }
}
/// QueryDelegatorUnbondingDelegationsRequest is request type for the
/// Query/DelegatorUnbondingDelegations RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryDelegatorUnbondingDelegationsRequest {
    /// delegator_addr defines the delegator address to query for.
    #[prost(string, tag = "1")]
    pub delegator_addr: ::prost::alloc::string::String,
    /// pagination defines an optional pagination for the request.
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<
        super::super::base::query::v1beta1::PageRequest,
    >,
}
impl ::prost::Name for QueryDelegatorUnbondingDelegationsRequest {
    const NAME: &'static str = "QueryDelegatorUnbondingDelegationsRequest";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryDelegatorUnbondingDelegationsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryDelegatorUnbondingDelegationsRequest".into()
    }
}
/// QueryUnbondingDelegatorDelegationsResponse is response type for the
/// Query/UnbondingDelegatorDelegations RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryDelegatorUnbondingDelegationsResponse {
    #[prost(message, repeated, tag = "1")]
    pub unbonding_responses: ::prost::alloc::vec::Vec<UnbondingDelegation>,
    /// pagination defines the pagination in the response.
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<
        super::super::base::query::v1beta1::PageResponse,
    >,
}
impl ::prost::Name for QueryDelegatorUnbondingDelegationsResponse {
    const NAME: &'static str = "QueryDelegatorUnbondingDelegationsResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryDelegatorUnbondingDelegationsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryDelegatorUnbondingDelegationsResponse".into()
    }
}
/// QueryRedelegationsRequest is request type for the Query/Redelegations RPC
/// method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRedelegationsRequest {
    /// delegator_addr defines the delegator address to query for.
    #[prost(string, tag = "1")]
    pub delegator_addr: ::prost::alloc::string::String,
    /// src_validator_addr defines the validator address to redelegate from.
    #[prost(string, tag = "2")]
    pub src_validator_addr: ::prost::alloc::string::String,
    /// dst_validator_addr defines the validator address to redelegate to.
    #[prost(string, tag = "3")]
    pub dst_validator_addr: ::prost::alloc::string::String,
    /// pagination defines an optional pagination for the request.
    #[prost(message, optional, tag = "4")]
    pub pagination: ::core::option::Option<
        super::super::base::query::v1beta1::PageRequest,
    >,
}
impl ::prost::Name for QueryRedelegationsRequest {
    const NAME: &'static str = "QueryRedelegationsRequest";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryRedelegationsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryRedelegationsRequest".into()
    }
}
/// QueryRedelegationsResponse is response type for the Query/Redelegations RPC
/// method.
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryRedelegationsResponse {
    #[prost(message, repeated, tag = "1")]
    pub redelegation_responses: ::prost::alloc::vec::Vec<RedelegationResponse>,
    /// pagination defines the pagination in the response.
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<
        super::super::base::query::v1beta1::PageResponse,
    >,
}
impl ::prost::Name for QueryRedelegationsResponse {
    const NAME: &'static str = "QueryRedelegationsResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryRedelegationsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryRedelegationsResponse".into()
    }
}
/// QueryDelegatorValidatorsRequest is request type for the
/// Query/DelegatorValidators RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryDelegatorValidatorsRequest {
    /// delegator_addr defines the delegator address to query for.
    #[prost(string, tag = "1")]
    pub delegator_addr: ::prost::alloc::string::String,
    /// pagination defines an optional pagination for the request.
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<
        super::super::base::query::v1beta1::PageRequest,
    >,
}
impl ::prost::Name for QueryDelegatorValidatorsRequest {
    const NAME: &'static str = "QueryDelegatorValidatorsRequest";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryDelegatorValidatorsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryDelegatorValidatorsRequest".into()
    }
}
/// QueryDelegatorValidatorsResponse is response type for the
/// Query/DelegatorValidators RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryDelegatorValidatorsResponse {
    /// validators defines the validators' info of a delegator.
    #[prost(message, repeated, tag = "1")]
    pub validators: ::prost::alloc::vec::Vec<Validator>,
    /// pagination defines the pagination in the response.
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<
        super::super::base::query::v1beta1::PageResponse,
    >,
}
impl ::prost::Name for QueryDelegatorValidatorsResponse {
    const NAME: &'static str = "QueryDelegatorValidatorsResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryDelegatorValidatorsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryDelegatorValidatorsResponse".into()
    }
}
/// QueryDelegatorValidatorRequest is request type for the
/// Query/DelegatorValidator RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryDelegatorValidatorRequest {
    /// delegator_addr defines the delegator address to query for.
    #[prost(string, tag = "1")]
    pub delegator_addr: ::prost::alloc::string::String,
    /// validator_addr defines the validator address to query for.
    #[prost(string, tag = "2")]
    pub validator_addr: ::prost::alloc::string::String,
}
impl ::prost::Name for QueryDelegatorValidatorRequest {
    const NAME: &'static str = "QueryDelegatorValidatorRequest";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryDelegatorValidatorRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryDelegatorValidatorRequest".into()
    }
}
/// QueryDelegatorValidatorResponse response type for the
/// Query/DelegatorValidator RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryDelegatorValidatorResponse {
    /// validator defines the validator info.
    #[prost(message, optional, tag = "1")]
    pub validator: ::core::option::Option<Validator>,
}
impl ::prost::Name for QueryDelegatorValidatorResponse {
    const NAME: &'static str = "QueryDelegatorValidatorResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryDelegatorValidatorResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryDelegatorValidatorResponse".into()
    }
}
/// QueryHistoricalInfoRequest is request type for the Query/HistoricalInfo RPC
/// method.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryHistoricalInfoRequest {
    /// height defines at which height to query the historical info.
    #[prost(int64, tag = "1")]
    pub height: i64,
}
impl ::prost::Name for QueryHistoricalInfoRequest {
    const NAME: &'static str = "QueryHistoricalInfoRequest";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryHistoricalInfoRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryHistoricalInfoRequest".into()
    }
}
/// QueryHistoricalInfoResponse is response type for the Query/HistoricalInfo RPC
/// method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryHistoricalInfoResponse {
    /// hist defines the historical info at the given height.
    #[prost(message, optional, tag = "1")]
    pub hist: ::core::option::Option<HistoricalInfo>,
}
impl ::prost::Name for QueryHistoricalInfoResponse {
    const NAME: &'static str = "QueryHistoricalInfoResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryHistoricalInfoResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryHistoricalInfoResponse".into()
    }
}
/// QueryPoolRequest is request type for the Query/Pool RPC method.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryPoolRequest {}
impl ::prost::Name for QueryPoolRequest {
    const NAME: &'static str = "QueryPoolRequest";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryPoolRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryPoolRequest".into()
    }
}
/// QueryPoolResponse is response type for the Query/Pool RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryPoolResponse {
    /// pool defines the pool info.
    #[prost(message, optional, tag = "1")]
    pub pool: ::core::option::Option<Pool>,
}
impl ::prost::Name for QueryPoolResponse {
    const NAME: &'static str = "QueryPoolResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryPoolResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryPoolResponse".into()
    }
}
/// QueryParamsRequest is request type for the Query/Params RPC method.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryParamsRequest {}
impl ::prost::Name for QueryParamsRequest {
    const NAME: &'static str = "QueryParamsRequest";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryParamsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryParamsRequest".into()
    }
}
/// QueryParamsResponse is response type for the Query/Params RPC method.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryParamsResponse {
    /// params holds all the parameters of this module.
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<Params>,
}
impl ::prost::Name for QueryParamsResponse {
    const NAME: &'static str = "QueryParamsResponse";
    const PACKAGE: &'static str = "cosmos.staking.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.staking.v1beta1.QueryParamsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.staking.v1beta1.QueryParamsResponse".into()
    }
}
/// Generated client implementations.
#[cfg(not(target_arch = "wasm32"))]
pub mod query_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Query defines the gRPC querier service.
    #[derive(Debug, Clone)]
    pub struct QueryClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl<T> QueryClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> QueryClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            QueryClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Validators queries all validators that match the given status.
        pub async fn validators(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryValidatorsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryValidatorsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.staking.v1beta1.Query/Validators",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cosmos.staking.v1beta1.Query", "Validators"));
            self.inner.unary(req, path, codec).await
        }
        /// Validator queries validator info for given validator address.
        pub async fn validator(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryValidatorRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryValidatorResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.staking.v1beta1.Query/Validator",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cosmos.staking.v1beta1.Query", "Validator"));
            self.inner.unary(req, path, codec).await
        }
        /// ValidatorDelegations queries delegate info for given validator.
        pub async fn validator_delegations(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryValidatorDelegationsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryValidatorDelegationsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.staking.v1beta1.Query/ValidatorDelegations",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cosmos.staking.v1beta1.Query",
                        "ValidatorDelegations",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// ValidatorUnbondingDelegations queries unbonding delegations of a validator.
        pub async fn validator_unbonding_delegations(
            &mut self,
            request: impl tonic::IntoRequest<
                super::QueryValidatorUnbondingDelegationsRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<super::QueryValidatorUnbondingDelegationsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.staking.v1beta1.Query/ValidatorUnbondingDelegations",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cosmos.staking.v1beta1.Query",
                        "ValidatorUnbondingDelegations",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Delegation queries delegate info for given validator delegator pair.
        pub async fn delegation(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryDelegationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryDelegationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.staking.v1beta1.Query/Delegation",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cosmos.staking.v1beta1.Query", "Delegation"));
            self.inner.unary(req, path, codec).await
        }
        /// UnbondingDelegation queries unbonding info for given validator delegator
        /// pair.
        pub async fn unbonding_delegation(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryUnbondingDelegationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryUnbondingDelegationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.staking.v1beta1.Query/UnbondingDelegation",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cosmos.staking.v1beta1.Query",
                        "UnbondingDelegation",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// DelegatorDelegations queries all delegations of a given delegator address.
        pub async fn delegator_delegations(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryDelegatorDelegationsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryDelegatorDelegationsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.staking.v1beta1.Query/DelegatorDelegations",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cosmos.staking.v1beta1.Query",
                        "DelegatorDelegations",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// DelegatorUnbondingDelegations queries all unbonding delegations of a given
        /// delegator address.
        pub async fn delegator_unbonding_delegations(
            &mut self,
            request: impl tonic::IntoRequest<
                super::QueryDelegatorUnbondingDelegationsRequest,
            >,
        ) -> std::result::Result<
            tonic::Response<super::QueryDelegatorUnbondingDelegationsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.staking.v1beta1.Query/DelegatorUnbondingDelegations",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cosmos.staking.v1beta1.Query",
                        "DelegatorUnbondingDelegations",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Redelegations queries redelegations of given address.
        pub async fn redelegations(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryRedelegationsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryRedelegationsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.staking.v1beta1.Query/Redelegations",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cosmos.staking.v1beta1.Query", "Redelegations"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// DelegatorValidators queries all validators info for given delegator
        /// address.
        pub async fn delegator_validators(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryDelegatorValidatorsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryDelegatorValidatorsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.staking.v1beta1.Query/DelegatorValidators",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cosmos.staking.v1beta1.Query",
                        "DelegatorValidators",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// DelegatorValidator queries validator info for given delegator validator
        /// pair.
        pub async fn delegator_validator(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryDelegatorValidatorRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryDelegatorValidatorResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.staking.v1beta1.Query/DelegatorValidator",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cosmos.staking.v1beta1.Query", "DelegatorValidator"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// HistoricalInfo queries the historical info for given height.
        pub async fn historical_info(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryHistoricalInfoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryHistoricalInfoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.staking.v1beta1.Query/HistoricalInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cosmos.staking.v1beta1.Query", "HistoricalInfo"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Pool queries the pool info.
        pub async fn pool(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryPoolRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryPoolResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.staking.v1beta1.Query/Pool",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cosmos.staking.v1beta1.Query", "Pool"));
            self.inner.unary(req, path, codec).await
        }
        /// Parameters queries the staking parameters.
        pub async fn params(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryParamsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::QueryParamsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cosmos.staking.v1beta1.Query/Params",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cosmos.staking.v1beta1.Query", "Params"));
            self.inner.unary(req, path, codec).await
        }
    }
}
