// This file is @generated by prost-build.
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExtendedHeader {
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<
        ::celestia_tendermint_proto::v0_34::types::Header,
    >,
    #[prost(message, optional, tag = "2")]
    pub commit: ::core::option::Option<
        ::celestia_tendermint_proto::v0_34::types::Commit,
    >,
    #[prost(message, optional, tag = "3")]
    pub validator_set: ::core::option::Option<
        ::celestia_tendermint_proto::v0_34::types::ValidatorSet,
    >,
    #[prost(message, optional, tag = "4")]
    pub dah: ::core::option::Option<
        super::super::celestia::core::v1::da::DataAvailabilityHeader,
    >,
}
impl ::prost::Name for ExtendedHeader {
    const NAME: &'static str = "ExtendedHeader";
    const PACKAGE: &'static str = "header.pb";
    fn full_name() -> ::prost::alloc::string::String {
        "header.pb.ExtendedHeader".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/header.pb.ExtendedHeader".into()
    }
}
