// This file is @generated by prost-build.
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Row {
    #[prost(message, repeated, tag = "1")]
    pub shares_half: ::prost::alloc::vec::Vec<Share>,
    #[prost(enumeration = "row::HalfSide", tag = "2")]
    pub half_side: i32,
}
/// Nested message and enum types in `Row`.
pub mod row {
    #[derive(::serde::Deserialize, ::serde::Serialize)]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum HalfSide {
        Left = 0,
        Right = 1,
    }
    impl HalfSide {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Left => "LEFT",
                Self::Right => "RIGHT",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "LEFT" => Some(Self::Left),
                "RIGHT" => Some(Self::Right),
                _ => None,
            }
        }
    }
}
impl ::prost::Name for Row {
    const NAME: &'static str = "Row";
    const PACKAGE: &'static str = "shwap";
    fn full_name() -> ::prost::alloc::string::String {
        "shwap.Row".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/shwap.Row".into()
    }
}
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Sample {
    #[prost(message, optional, tag = "1")]
    pub share: ::core::option::Option<Share>,
    #[prost(message, optional, tag = "2")]
    pub proof: ::core::option::Option<super::proof::pb::Proof>,
    #[prost(enumeration = "AxisType", tag = "3")]
    pub proof_type: i32,
}
impl ::prost::Name for Sample {
    const NAME: &'static str = "Sample";
    const PACKAGE: &'static str = "shwap";
    fn full_name() -> ::prost::alloc::string::String {
        "shwap.Sample".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/shwap.Sample".into()
    }
}
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RowNamespaceData {
    #[prost(message, repeated, tag = "1")]
    #[serde(with = "crate::serializers::null_default")]
    pub shares: ::prost::alloc::vec::Vec<Share>,
    #[prost(message, optional, tag = "2")]
    pub proof: ::core::option::Option<super::proof::pb::Proof>,
}
impl ::prost::Name for RowNamespaceData {
    const NAME: &'static str = "RowNamespaceData";
    const PACKAGE: &'static str = "shwap";
    fn full_name() -> ::prost::alloc::string::String {
        "shwap.RowNamespaceData".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/shwap.RowNamespaceData".into()
    }
}
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[serde(transparent)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Share {
    #[prost(bytes = "vec", tag = "1")]
    #[serde(with = "celestia_tendermint_proto::serializers::bytes::base64string")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for Share {
    const NAME: &'static str = "Share";
    const PACKAGE: &'static str = "shwap";
    fn full_name() -> ::prost::alloc::string::String {
        "shwap.Share".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/shwap.Share".into()
    }
}
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AxisType {
    Row = 0,
    Col = 1,
}
impl AxisType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Row => "ROW",
            Self::Col => "COL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ROW" => Some(Self::Row),
            "COL" => Some(Self::Col),
            _ => None,
        }
    }
}
