[workspace]
resolver = "2"
members = ["celestia", "node", "proto", "rpc", "types"]

[workspace.dependencies]
celestia-node = { version = "0.1.0", path = "node" }
celestia-proto = { version = "0.1.0", path = "proto" }
celestia-rpc = { version = "0.1.0", path = "rpc", default-features = false }
celestia-types = { version = "0.1.0", path = "types", default-features = false }
nmt-rs = { git = "https://github.com/Sovereign-Labs/nmt-rs.git", rev = "d821332" }
tendermint = { git = "https://github.com/eigerco/celestia-tendermint-rs.git", rev = "1f8b574", default-features = false }
tendermint-proto = { git = "https://github.com/eigerco/celestia-tendermint-rs.git", rev = "1f8b574" }

[patch.'https://github.com/eigerco/celestia-tendermint-rs.git']
# Uncomment to apply local changes
#tendermint = { path = "../celestia-tendermint-rs/tendermint" }
#tendermint-proto = { path = "../celestia-tendermint-rs/proto" }

[patch.crates-io]
wasm-bindgen-futures = { path = "../wasm-bindgen/crates/futures" }
wasm-bindgen = { path = "../wasm-bindgen/" }
wasm-bindgen-cli = { path = "../wasm-bindgen/crates/cli" }
js-sys = { path = "../wasm-bindgen/crates/js-sys" }
web-sys = { path = "../wasm-bindgen/crates/web-sys" }
gloo-timers = { path = "../gloo/crates/timers" }

[patch.'https://github.com/eigerco/nmt-rs.git']
# Uncomment to apply local changes
#nmt-rs = { path = "../nmt-rs" }
