// This file is @generated by prost-build.
/// Params defines the parameters for the module.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Params {
    #[prost(uint32, tag = "1")]
    pub gas_per_blob_byte: u32,
    #[prost(uint64, tag = "2")]
    pub gov_max_square_size: u64,
}
/// QueryParamsRequest is the request type for the Query/Params RPC method.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryParamsRequest {}
/// QueryParamsResponse is the response type for the Query/Params RPC method.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryParamsResponse {
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<Params>,
}
/// MsgPayForBlobs pays for the inclusion of a blob in the block.
#[derive(::serde::Deserialize, ::serde::Serialize)]
#[serde(default)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgPayForBlobs {
    /// signer is the bech32 encoded signer address. See
    /// <https://en.bitcoin.it/wiki/Bech32.>
    #[prost(string, tag = "1")]
    pub signer: ::prost::alloc::string::String,
    /// namespaces is a list of namespaces that the blobs are associated with. A
    /// namespace is a byte slice of length 29 where the first byte is the
    /// namespaceVersion and the subsequent 28 bytes are the namespaceId.
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub namespaces: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// blob_sizes is a list of blob sizes (one per blob). Each size is in bytes.
    #[prost(uint32, repeated, tag = "3")]
    pub blob_sizes: ::prost::alloc::vec::Vec<u32>,
    /// share_commitments is a list of share commitments (one per blob).
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub share_commitments: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// share_versions are the versions of the share format that the blobs
    /// associated with this message should use when included in a block. The
    /// share_versions specified must match the share_versions used to generate the
    /// share_commitment in this message.
    #[prost(uint32, repeated, tag = "8")]
    pub share_versions: ::prost::alloc::vec::Vec<u32>,
}
/// MsgPayForBlobsResponse describes the response returned after the submission
/// of a PayForBlobs
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgPayForBlobsResponse {}
