// This file is @generated by prost-build.
pub mod bitswap {
    include!(concat!(env!("OUT_DIR"), "/bitswap.rs"));
}
pub mod celestia {
    pub mod blob {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/celestia.blob.v1.rs"));
        }
    }
    pub mod core {
        pub mod v1 {
            pub mod da {
                include!(concat!(env!("OUT_DIR"), "/celestia.core.v1.da.rs"));
            }
        }
    }
}
pub mod cosmos {
    pub mod auth {
        pub mod v1beta1 {
            include!(concat!(env!("OUT_DIR"), "/cosmos.auth.v1beta1.rs"));
        }
    }
    pub mod base {
        pub mod abci {
            pub mod v1beta1 {
                include!(concat!(env!("OUT_DIR"), "/cosmos.base.abci.v1beta1.rs"));
            }
        }
        pub mod node {
            pub mod v1beta1 {
                include!(concat!(env!("OUT_DIR"), "/cosmos.base.node.v1beta1.rs"));
            }
        }
        pub mod query {
            pub mod v1beta1 {
                include!(concat!(env!("OUT_DIR"), "/cosmos.base.query.v1beta1.rs"));
            }
        }
        pub mod tendermint {
            pub mod v1beta1 {
                include!(concat!(env!("OUT_DIR"), "/cosmos.base.tendermint.v1beta1.rs"));
            }
        }
        pub mod v1beta1 {
            include!(concat!(env!("OUT_DIR"), "/cosmos.base.v1beta1.rs"));
        }
    }
    pub mod crypto {
        pub mod multisig {
            pub mod v1beta1 {
                include!(concat!(env!("OUT_DIR"), "/cosmos.crypto.multisig.v1beta1.rs"));
            }
        }
        pub mod secp256k1 {
            include!(concat!(env!("OUT_DIR"), "/cosmos.crypto.secp256k1.rs"));
        }
    }
    pub mod staking {
        pub mod v1beta1 {
            include!(concat!(env!("OUT_DIR"), "/cosmos.staking.v1beta1.rs"));
        }
    }
    pub mod tx {
        pub mod signing {
            pub mod v1beta1 {
                include!(concat!(env!("OUT_DIR"), "/cosmos.tx.signing.v1beta1.rs"));
            }
        }
        pub mod v1beta1 {
            include!(concat!(env!("OUT_DIR"), "/cosmos.tx.v1beta1.rs"));
        }
    }
}
pub mod cosmos_proto {
    include!(concat!(env!("OUT_DIR"), "/cosmos_proto.rs"));
}
pub mod google {
    pub mod api {
        include!(concat!(env!("OUT_DIR"), "/google.api.rs"));
    }
}
pub mod header {
    pub mod pb {
        include!(concat!(env!("OUT_DIR"), "/header.pb.rs"));
    }
}
pub mod p2p {
    pub mod pb {
        include!(concat!(env!("OUT_DIR"), "/p2p.pb.rs"));
    }
}
pub mod proof {
    pub mod pb {
        include!(concat!(env!("OUT_DIR"), "/proof.pb.rs"));
    }
}
pub mod share {
    pub mod eds {
        pub mod byzantine {
            pub mod pb {
                include!(concat!(env!("OUT_DIR"), "/share.eds.byzantine.pb.rs"));
            }
        }
    }
}
pub mod shwap {
    include!(concat!(env!("OUT_DIR"), "/shwap.rs"));
}
