[package]
name = "celestia-node"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
celestia-proto = { workspace = true }
celestia-types = { workspace = true }
tendermint-proto = { workspace = true }

async-trait = "0.1.73"
dashmap = "5.5.3"
futures = "0.3.28"
instant = "0.1.12"
libp2p = { version = "0.52.3", features = [
  "autonat",
  "ping",
  "gossipsub",
  "identify",
  "macros",
  "request-response",
  "kad",
] }
prost = "0.12.0"
rand = "0.8.5"
smallvec = { version = "1.11.1", features = ["union", "const_generics"] }
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["macros", "sync", "time"] }
tracing = "0.1.37"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
directories = "5.0.1"
# Upgrading this dependency invalidates existing persistent dbs.
# Those can be restored by migrating between versions:
# https://docs.rs/sled/latest/sled/struct.Db.html#examples-1
sled = "0.34.7"
tempdir = "0.3.7"
tokio = { version = "1.32.0", features = ["rt-multi-thread", "time"] }
libp2p = { version = "0.52.3", features = [
  "noise",
  "dns",
  "tcp",
  "tokio",
  "yamux",
  "quic",
] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.10", features = ["js"] }
gloo-timers = { version = "0.3.0", features = ["futures"] }
rexie = "0.5.0"
send_wrapper = { version = "0.6.0", features = ["futures"] }
serde = { version = "1.0.164", features = ["derive"] }
serde-wasm-bindgen = "0.6.0"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
libp2p = { version = "0.52.3", features = ["webtransport-websys"] }
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
futures-timer = { version = "3.0.2", features = ["wasm-bindgen"]}
pin-project = "1.1.3"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
tokio = { version = "1.32.0", features = ["time" ] }
wasm-bindgen-test = "0.3"
function_name = "0.3.0"

[dev-dependencies]
bytes = "1.4.0"
celestia-node = { workspace = true, features = ["test-utils"] }
celestia-rpc = { workspace = true, features = ["p2p"] }
celestia-types = { workspace = true, features = ["test-utils"] }
dotenvy = "0.15.7"
serde_json = "1.0.107"

[features]
test-utils = ["celestia-types/test-utils"]
